name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: caffeinelabs/setup-mops@v1

      - name: Install icp-cli
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/dfinity/icp-cli/releases/download/v0.1.0-beta.6/icp-cli-installer.sh | sh

      - name: Confirm icp-cli version
        run: icp --version

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: run tests
        run: mops test

      - name: Build minimal example
        working-directory: ./examples
        run: icp build minimal

      - name: Build main example
        working-directory: ./examples
        run: icp build main

      - name: Build advanced example
        working-directory: ./examples
        run: icp build advanced

      - name: Build heatmap example
        working-directory: ./examples
        run: icp build heatmap

      - name: Build http example
        working-directory: ./examples
        run: icp build http
