name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: caffeinelabs/setup-mops@v1

      - name: Install icp-cli
        run: npm install -g @icp-sdk/icp-cli @icp-sdk/ic-wasm

      - name: Confirm versions
        run: |
          mops --version
          icp --version
          ic-wasm --version

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Prettier Check and Format
        run: |
          npm install prettier prettier-plugin-motoko --no-save
          npx -y prettier --plugin prettier-plugin-motoko --write '**/*.{mo,json,md}'

      - name: Commit formatted files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git diff-index --quiet HEAD || (git commit -m "chore: format code with prettier" && git push origin HEAD:${{ github.head_ref }})

      - name: run tests
        run: mops test

      - name: Build minimal example
        working-directory: ./examples
        run: icp build
