name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: caffeinelabs/setup-mops@v1

      - name: Install icp-cli
        run: npm install -g @icp-sdk/icp-cli @icp-sdk/ic-wasm

      - name: Confirm versions
        run: |
          mops --version
          icp --version
          ic-wasm --version

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: run tests
        run: mops test

      - name: Prettier Check
        run: npx -p prettier -p prettier-plugin-motoko prettier --plugin prettier-plugin-motoko --check '**/*.{mo,json,md}'

      - name: Build minimal example
        working-directory: ./examples
        run: icp build
